import { readFileSync, rmSync } from "fs";
import { join } from "path";

import { PackageManager, getWorkspaceDep } from "../../types.js";
import { run } from "../../utils/exec.js";
import { editJson, templatePath, writeText } from "../../utils/fs.js";

const DEFAULT_PRESET =
  "https://ui.shadcn.com/init?base=base&style=vega&baseColor=neutral&theme=blue&iconLibrary=lucide&font=inter&menuAccent=subtle&menuColor=default&radius=default&template=next&rtl=false";

export function setupNextjs(
  dir: string,
  pm: PackageManager,
  dlx: string,
  presetUrl?: string,
) {
  const appsDir = join(dir, "apps");
  const urlMatch = presetUrl?.match(/https?:\/\/[^\s"]+/);
  const preset = urlMatch ? urlMatch[0] : DEFAULT_PRESET;

  run(
    `${dlx} shadcn@latest create --preset "${preset}" --template next -- web`,
    appsDir,
  );

  const webDir = join(appsDir, "web");

  // Remove default README generated by shadcn
  rmSync(join(webDir, "README.md"), { force: true });

  // Remove .gitignore
  rmSync(join(webDir, ".gitignore"), { force: true });

  // tsconfig.json
  const tsconfig = readFileSync(
    templatePath(import.meta.url, "tsconfig.json"),
    "utf-8",
  );
  writeText(join(webDir, "tsconfig.json"), tsconfig);

  // next.config.ts (standalone output for Docker)
  const nextConfig = readFileSync(
    templatePath(import.meta.url, "next.config.ts"),
    "utf-8",
  );
  writeText(join(webDir, "next.config.ts"), nextConfig);

  // eslint config
  const eslintConfig = readFileSync(
    templatePath(import.meta.url, "eslint.config.mjs"),
    "utf-8",
  );
  writeText(join(webDir, "eslint.config.mjs"), eslintConfig);

  // Update package.json
  const ws = getWorkspaceDep(pm);
  editJson(join(webDir, "package.json"), (pkg) => {
    pkg.scripts["check-types"] = "tsc --noEmit";
    pkg.dependencies["@repo/db"] = ws;
    pkg.devDependencies["@repo/eslint-config"] = ws;
    pkg.devDependencies["@repo/typescript-config"] = ws;
    delete pkg.devDependencies["eslint-config-next"];
  });

  // Remove standalone lock/workspace files
  rmSync(join(webDir, "pnpm-lock.yaml"), { force: true });
  rmSync(join(webDir, "pnpm-workspace.yaml"), { force: true });
}
